// Trading Constants
export const TRADING_CATEGORIES = {
  NIFTY_50: 'Nifty 50',
  SECTORS: 'Sectors',
  FAVORITES: 'Favorites',
} as const;

export const MARKET_INDICES = [
  {
    name: 'NIFTY 50',
    value: '19,674.25',
    change: '+124.75',
    changePercent: '+0.64%',
    isPositive: true,
  },
  {
    name: 'SENSEX',
    value: '65,982.48',
    change: '+456.32',
    changePercent: '+0.70%',
    isPositive: true,
  },
  {
    name: 'BANK NIFTY',
    value: '44,123.67',
    change: '-89.45',
    changePercent: '-0.20%',
    isPositive: false,
  },
];

export const STOCK_DATA = [
  {
    symbol: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    price: '₹2,456.80',
    change: '+2.45%',
    changeValue: '+58.75',
    isPositive: true,
    exchange: 'NSE',
    isFavorite: false,
    volume: '2.5M',
    marketCap: '₹16.2T',
  },
  {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    price: '₹3,789.25',
    change: '-1.23%',
    changeValue: '-47.15',
    isPositive: false,
    exchange: 'NSE',
    isFavorite: true,
    volume: '1.8M',
    marketCap: '₹13.9T',
  },
  {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Limited',
    price: '₹1,634.90',
    change: '+0.87%',
    changeValue: '+14.12',
    isPositive: true,
    exchange: 'NSE',
    isFavorite: false,
    volume: '3.2M',
    marketCap: '₹9.1T',
  },
  {
    symbol: 'INFY',
    name: 'Infosys Limited',
    price: '₹1,456.30',
    change: '-0.45%',
    changeValue: '-6.58',
    isPositive: false,
    exchange: 'NSE',
    isFavorite: true,
    volume: '2.1M',
    marketCap: '₹6.1T',
  },
  {
    symbol: 'ITC',
    name: 'ITC Limited',
    price: '₹428.75',
    change: '+1.89%',
    changeValue: '+7.95',
    isPositive: true,
    exchange: 'NSE',
    isFavorite: false,
    volume: '4.7M',
    marketCap: '₹5.4T',
  },
  {
    symbol: 'ICICIBANK',
    name: 'ICICI Bank Limited',
    price: '₹987.45',
    change: '+0.32%',
    changeValue: '+3.15',
    isPositive: true,
    exchange: 'NSE',
    isFavorite: false,
    volume: '5.1M',
    marketCap: '₹6.8T',
  },
  {
    symbol: 'SBIN',
    name: 'State Bank of India',
    price: '₹634.20',
    change: '-0.78%',
    changeValue: '-4.98',
    isPositive: false,
    exchange: 'NSE',
    isFavorite: false,
    volume: '8.9M',
    marketCap: '₹5.7T',
  },
  {
    symbol: 'BHARTIARTL',
    name: 'Bharti Airtel Limited',
    price: '₹892.60',
    change: '+1.56%',
    changeValue: '+13.70',
    isPositive: true,
    exchange: 'NSE',
    isFavorite: true,
    volume: '3.4M',
    marketCap: '₹5.3T',
  },
];

export const PORTFOLIO_DATA = {
  totalValue: '₹125,450',
  totalInvested: '₹98,750',
  totalProfit: '+₹26,700',
  profitPercentage: '+27.04%',
  todayProfit: '+₹2,450',
  todayProfitPercentage: '+1.99%',
  cashBalance: '₹15,230',
  totalTrades: 24,
  winningTrades: 18,
  losingTrades: 6,
  winRate: '75%',
};

export const PORTFOLIO_HOLDINGS = [
  {
    symbol: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    quantity: 10,
    avgPrice: '₹2,398.05',
    currentPrice: '₹2,456.80',
    marketValue: '₹24,568',
    profit: '+₹588',
    profitPercentage: '+2.45%',
    isPositive: true,
  },
  {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    quantity: 5,
    avgPrice: '₹3,836.40',
    currentPrice: '₹3,789.25',
    marketValue: '₹18,946',
    profit: '-₹236',
    profitPercentage: '-1.23%',
    isPositive: false,
  },
  {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Limited',
    quantity: 15,
    avgPrice: '₹1,620.78',
    currentPrice: '₹1,634.90',
    marketValue: '₹24,524',
    profit: '+₹212',
    profitPercentage: '+0.87%',
    isPositive: true,
  },
  {
    symbol: 'INFY',
    name: 'Infosys Limited',
    quantity: 20,
    avgPrice: '₹1,462.88',
    currentPrice: '₹1,456.30',
    marketValue: '₹29,126',
    profit: '-₹132',
    profitPercentage: '-0.45%',
    isPositive: false,
  },
];

export const SECTOR_ALLOCATION = [
  { sector: 'Technology', percentage: 35, color: '#3B82F6' },
  { sector: 'Banking', percentage: 25, color: '#10B981' },
  { sector: 'Oil & Gas', percentage: 20, color: '#F59E0B' },
  { sector: 'Consumer Goods', percentage: 15, color: '#EF4444' },
  { sector: 'Others', percentage: 5, color: '#8B5CF6' },
];

export const ORDER_HISTORY = [
  {
    id: '1',
    symbol: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    type: 'BUY' as const,
    quantity: 10,
    price: '₹2,398.05',
    total: '₹23,980.50',
    status: 'COMPLETED' as const,
    date: '2024-01-15',
    time: '10:30 AM',
    profit: '+₹588',
    profitPercentage: '+2.45%',
    isPositive: true,
  },
  {
    id: '2',
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    type: 'SELL' as const,
    quantity: 3,
    price: '₹3,850.00',
    total: '₹11,550.00',
    status: 'COMPLETED' as const,
    date: '2024-01-14',
    time: '02:15 PM',
    profit: '+₹1,200',
    profitPercentage: '+11.6%',
    isPositive: true,
  },
  {
    id: '3',
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Limited',
    type: 'BUY' as const,
    quantity: 15,
    price: '₹1,620.78',
    total: '₹24,311.70',
    status: 'COMPLETED' as const,
    date: '2024-01-13',
    time: '09:45 AM',
    profit: '+₹212',
    profitPercentage: '+0.87%',
    isPositive: true,
  },
  {
    id: '4',
    symbol: 'INFY',
    name: 'Infosys Limited',
    type: 'BUY' as const,
    quantity: 20,
    price: '₹1,462.88',
    total: '₹29,257.60',
    status: 'PENDING' as const,
    date: '2024-01-12',
    time: '11:20 AM',
    profit: '-₹132',
    profitPercentage: '-0.45%',
    isPositive: false,
  },
];

export const LEADERBOARD_DATA = [
  {
    rank: 1,
    name: 'Rahul Sharma',
    username: '@rahul_trader',
    totalReturn: '+45.67%',
    totalValue: '₹2,45,670',
    trades: 156,
    winRate: '78%',
    isCurrentUser: false,
  },
  {
    rank: 2,
    name: 'Priya Patel',
    username: '@priya_investor',
    totalReturn: '+38.92%',
    totalValue: '₹1,89,230',
    trades: 89,
    winRate: '82%',
    isCurrentUser: false,
  },
  {
    rank: 3,
    name: 'Amit Kumar',
    username: '@amit_stocks',
    totalReturn: '+32.15%',
    totalValue: '₹1,56,780',
    trades: 234,
    winRate: '71%',
    isCurrentUser: false,
  },
  {
    rank: 4,
    name: 'Sarah Johnson',
    username: '@sarah_j',
    totalReturn: '+27.04%',
    totalValue: '₹1,25,450',
    trades: 24,
    winRate: '75%',
    isCurrentUser: true,
  },
  {
    rank: 5,
    name: 'Vikram Singh',
    username: '@vikram_trade',
    totalReturn: '+25.89%',
    totalValue: '₹1,18,920',
    trades: 67,
    winRate: '69%',
    isCurrentUser: false,
  },
];

export const ORDER_TYPES = {
  MARKET: 'MARKET',
  LIMIT: 'LIMIT',
  STOP_LOSS: 'STOP_LOSS',
} as const;

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
} as const;

export const TRADE_TYPES = {
  BUY: 'BUY',
  SELL: 'SELL',
} as const;

export const TIME_FRAMES = {
  DAY: '1D',
  WEEK: '1W',
  MONTH: '1M',
  QUARTER: '3M',
  YEAR: '1Y',
} as const;

export const CHART_TYPES = {
  LINE: 'LINE',
  CANDLESTICK: 'CANDLESTICK',
  BAR: 'BAR',
} as const;

// Stock Detail Constants
export const STOCK_DETAIL_DATA = {
  companyProfile: {
    description: 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company serves consumers, and small and mid-sized businesses.',
    founded: '1976',
    employees: '164,000',
    headquarters: 'Cupertino, CA',
    sector: 'Technology',
    industry: 'Consumer Electronics',
  },
  fundamentals: [
    { label: '52W High', value: '₹199.62' },
    { label: '52W Low', value: '₹124.17' },
    { label: 'Dividend Yield', value: '0.50%' },
    { label: 'EPS', value: '₹6.43' },
    { label: 'Beta', value: '1.24' },
    { label: 'ROE', value: '147.25%' },
  ],
  news: [
    {
      id: '1',
      title: 'Apple Reports Strong Q4 Earnings',
      source: 'Reuters',
      timeAgo: '2 hours ago',
      image: null,
    },
    {
      id: '2',
      title: 'iPhone 15 Sales Exceed Expectations',
      source: 'Bloomberg',
      timeAgo: '5 hours ago',
      image: null,
    },
  ],
};
