# Generated by Django 5.2.5 on 2025-09-03 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_quiz_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_courses', models.IntegerField(default=0)),
                ('completed_courses', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('completed_lessons', models.IntegerField(default=0)),
                ('total_quizzes', models.IntegerField(default=0)),
                ('completed_quizzes', models.IntegerField(default=0)),
                ('average_quiz_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_learning_hours', models.IntegerField(default=0)),
                ('portfolio_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('portfolio_growth_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_trades', models.IntegerField(default=0)),
                ('successful_trades', models.IntegerField(default=0)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_badges', models.IntegerField(default=0)),
                ('earned_badges', models.IntegerField(default=0)),
                ('total_achievements', models.IntegerField(default=0)),
                ('earned_achievements', models.IntegerField(default=0)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_activity_days', models.IntegerField(default=0)),
                ('experience_points', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('experience_to_next_level', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Progress',
            },
        ),
        migrations.CreateModel(
            name='MonthlyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_lessons_completed', models.IntegerField(default=0)),
                ('total_quizzes_taken', models.IntegerField(default=0)),
                ('average_quiz_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_trades', models.IntegerField(default=0)),
                ('portfolio_growth', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('new_achievements', models.IntegerField(default=0)),
                ('new_badges', models.IntegerField(default=0)),
                ('goals_met', models.IntegerField(default=0)),
                ('total_goals', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('lessons_completed', models.IntegerField(default=0)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('learning_hours', models.IntegerField(default=0)),
                ('trades_made', models.IntegerField(default=0)),
                ('portfolio_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('activity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
