# Generated by Django 5.2.5 on 2026-06-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('as_of', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='avg_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='employees',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='founded',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='headquarters',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='api.stock')),
            ],
            options={
                'verbose_name_plural': 'Stock news',
                'ordering': ['-published_at'],
            },
        ),
    ]
