# Generated by Django 5.2.5 on 2026-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='gemini_model',
            field=models.CharField(blank=True, default='gemini-pro', max_length=100),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='openai_model',
            field=models.CharField(blank=True, default='gpt-4', max_length=100),
        ),
    ]
