# Generated by Django 5.2.5 on 2026-09-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ai_settings_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='aisettings',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'AI settings'},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='learningprogress',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='marketdata',
            options={'ordering': ['-change_percentage']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='portfolioholding',
            options={'ordering': ['-market_value']},
        ),
        migrations.AlterModelOptions(
            name='privacysettings',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='securitysettings',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterModelOptions(
            name='technicalindicator',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-executed_at']},
        ),
        migrations.AlterModelOptions(
            name='tradingperformance',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='tradingsession',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-earned_at']},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-earned_at']},
        ),
        migrations.AlterModelOptions(
            name='userlessonprogress',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'User Progress'},
        ),
        migrations.AlterModelOptions(
            name='userquizanswer',
            options={'ordering': ['-answered_at']},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userwatchlist',
            options={'ordering': ['-added_at']},
        ),
    ]
